version: '3.8'

services:
  wordpress:
    image: wordpress
    ports:
      - "5000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: wordpress1234
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: test
      MYSQL_PASSWORD: wordpress1234
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql:/var/lib/mysql

volumes:
  wordpress:
  mysql:
