---
- name: Collect IP interface details from Cisco vIOS
  hosts: vios
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Retrieve interface IP summary
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: ip_brief

    - name: Display interface IP information
      ansible.builtin.debug:
        msg: "show ip interface brief:\n{{ ip_brief.stdout[0] }}"

