---
- name: Check STP status for VLAN 1
  hosts: vios
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Show spanning-tree for VLAN 1
      cisco.ios.ios_command:
        commands:
          - show spanning-tree vlan 1
      register: stp_vlan1

    - name: Display STP VLAN 1 status
      ansible.builtin.debug:
        msg: |-
          Host: {{ inventory_hostname }}
          {{ stp_vlan1.stdout[0] | default('No STP data returned') }}
