---
- name: Check STP status for VLAN 12
  hosts: vios
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Show spanning-tree for VLAN 12
      cisco.ios.ios_command:
        commands:
          - show spanning-tree vlan 12
      register: stp_vlan12

    - name: Display STP VLAN 12 status
      ansible.builtin.debug:
        msg: |-
          Host: {{ inventory_hostname }}
          {{ stp_vlan12.stdout[0] | default('No STP data returned') }}
