---
- name: Show interface IP summary on switches
  hosts: vios
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Display all interfaces with IP information
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: ip_summary

    - name: Show summary output
      ansible.builtin.debug:
        msg: |-
          Host: {{ inventory_hostname }}
          {{ ip_summary.stdout[0] | default('No data returned') }}
