---
- name: Collect CDP neighbors from Cisco vIOS
  hosts: vios
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Retrieve CDP neighbor details
      cisco.ios.ios_command:
        commands:
          - show cdp neighbors detail
      register: cdp_detail

    - name: Display CDP neighbor information
      ansible.builtin.debug:
        msg: "show cdp neighbors detail:\n{{ cdp_detail.stdout[0] }}"

